env:
  browser: true
  node: true
  amd: true
  es6: true
extends: "eslint:recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {}
ignorePatterns: ["*test.js"]
